yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('', views.index, name='index'),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView
)
from django.urls import path, reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    # Страница выхода из УЗ
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),

    # страница регистрации
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),

    # страница входа
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),

    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'password_reset/confirm/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:password_change_done')
        ),
        name='password_reset_confirm'
    ),
    # страница сброса пароля
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            success_url=reverse_lazy('users:password_reset_done'),
        ),
        name='password_reset_form'
    ),

    # страница смены пароля
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html',
            success_url=reverse_lazy('users:password_change_done')
        ),
        name='password_change_form'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403 = 'core.views.page_permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.page_internal_server_error'

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    # Встроенная админка Django
    path('admin/', admin.site.urls, name='admin'),
    # urls для кастомного приложения users
    path('auth/', include('users.urls', namespace='users')),
    # urls модуля для управления пользователями
    path('auth/', include('django.contrib.auth.urls')),
    # Главная страница
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/comments.html
{% load user_filters %}
{% if user.is_authenticated %}
  {% if not comments %}
    <h6>У записи нет комментариев. Будьте первым!</h6>
  {% endif %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {% load user_filters %}
          {{ form.text|addclass:'form-control' }}
        </div>
        {% if request.user.is_authenticated %}
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary ">Отправить</button>
          </div>
        {% endif %}
      </form>
    </div>
  </div>
{% endif %}
{% if comments %}
  <h6>Комментарии наших пользователей</h6>
{% endif %}
{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <ul class="list-group list-group-horizontal justify-content-end">
        <li class="list-group-item" style="border: none">
          <a href="{% url 'posts:profile' comment.author.username %}">
            {{ comment.author.get_full_name }}
          </a>
        </li>
        <li class="list-group-item justify-content-end" style="border: none">
          {{ comment.created }}
        </li>
      </ul>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
  {% if not forloop.last %}
    <hr>
  {% endif %}
{% endfor %}

yatube/templates/includes/footer.html
<footer>
  <div class="border-top text-center py-3">
    <div class="container">
      <ul class="list-group list-group-horizontal justify-content-center">
        <li class="list-group-item" style="border: none">
          <a href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="list-group-item" style="border: none">
          <a href="{% url 'about:tech' %}">Технологии</a>
        </li>
      </ul>
    </div>
    <p>© 2022 Copyright <span style="color:red">Ya</span>tube</p>
  </div>
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img\\logo.png' %}"
             width="30"
             height="30"
             class="d-inline-block align-top"
             alt="">
        <span style="color:red">Ya</span>tube</a>
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.view_name  == '' %} active{% endif %} "
                 href="{% url 'posts:post_create' %}">Новая запись</a>
            </li>
            <li class="nav-item">
              <a class="nav-link  {% if view_name  == 'users:password_change_form' %} active {% endif %}  link-light"
                 href="{% url 'users:password_change_form' %}">
                Изменить пароль
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
            </li>
            <li>
              Пользователь:
              <a href="{% url 'posts:profile' user.username %}">
                {{ user.username }}
              </a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link  {% if view_name  == 'users:login' %} active {% endif %}  link-light"
                 href="{% url 'users:login' %}">
                Войти
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link  {% if view_name  == 'users:signup' %} active {% endif %}  link-light"
                 href="{% url 'users:signup' %}">
                Регистрация
              </a>
            </li>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Предыдущая
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Следующая
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a
                  class="nav-link {% if request.resolver_match.view_name  == 'posts:index' %} active{% endif %}"
                  href="{% url 'posts:index' %}"
          >
            Все авторы
          </a>
        </li>
        <li class="nav-item">
          <a
                  class="nav-link {% if request.resolver_match.view_name  == 'posts:follow_index' %} active{% endif %}"
                  href="{% url 'posts:follow_index' %}"
          >
            Избранные авторы
          </a>
        </li>
      </ul>
    {% endwith %}
  </div>
{% endif %}