yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('', views.index, name='index'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403 = 'core.views.page_permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.page_internal_server_error'

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    # Встроенная админка Django
    path('admin/', admin.site.urls, name='admin'),
    # urls для кастомного приложения users
    path('auth/', include('users.urls', namespace='users')),
    # urls модуля для управления пользователями
    path('auth/', include('django.contrib.auth.urls')),
    # Главная страница
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Заголовок'
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Код группы'
    )
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Группу'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(CreatedModel):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        upload_to='posts/',
        verbose_name='Картинка',
        help_text='Загрузите изображение',
        blank=True,
    )

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-created',)

    def __str__(self):
        return self.text[:15]


class Comment(CreatedModel):
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментриуемый пост'
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ('-created',)

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        ordering = ('author',)
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_follow'
            )
        ]

    def __str__(self):
        return f'{self.user} follows {self.author}'

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .settings import POSTS_ON_PAGE


def paginate(request, posts, posts_per_page=POSTS_ON_PAGE):
    """Функция пагинации"""
    return Paginator(posts, posts_per_page).get_page(request.GET.get('page'))


def index(request):
    """View-функция для главной страницы"""
    return render(request, 'posts/index.html', {
        'page_obj': paginate(request, Post.objects.all())
    })


def group_posts(request, slug):
    """View-функция для страницы с лентой группы"""
    group = get_object_or_404(Group, slug=slug)
    return render(request, 'posts/group_list.html', {
        'group': group,
        'page_obj': paginate(request, group.posts.all())
    })


def profile(request, username):
    """View-функция для страницы с лентой профиля"""
    author = get_object_or_404(User, username=username)
    following = request.user.is_authenticated and (
        Follow.objects.filter(
            user=request.user,
            author=author,
        ).exists()
    )
    return render(request, 'posts/profile.html', {
        'author': author,
        'page_obj': paginate(request, author.posts.all()),
        'following': following,
    })


def post_detail(request, post_id):
    """View-функция для страницы подробной информации о посте"""
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()
    form = CommentForm()
    return render(request, 'posts/post_detail.html', {
        'post': post,
        'form': form,
        'comments': comments,
    })


@login_required
def post_create(request):
    """View-функция для создания поста"""
    form = PostForm(request.POST or None, files=request.FILES or None,)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', request.user.username)


@login_required
def post_edit(request, post_id):
    """View-функция для редактирования поста"""
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {
            'form': form, 'post': post
        })
    form.save()
    return redirect('posts:post_detail', post_id)


@login_required
def add_comment(request, post_id):
    """View-функция для создания комментария"""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if not form.is_valid():
        return redirect('posts:post_detail', post_id=post_id)
    comment = form.save(commit=False)
    comment.author = request.user
    comment.post = post
    comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """View-функция для страницы с лентой постов избранных авторов"""
    context = {
        'page_obj': paginate(
            request,
            Post.objects.filter(author__following__user=request.user)
        )
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """View-функция для подписки на автора"""
    author = get_object_or_404(User, username=username)
    if author == request.user:
        return redirect('posts:follow_index')
    Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    """View-функция для отписки от автора"""
    Follow.objects.filter(
        author=get_object_or_404(User, username=username),
        user=request.user
    ).delete()
    return redirect('posts:follow_index')

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
<!--Существует ли post.id?-->
{% block title %}
  {% if post %}Редактировать пост{% else %}Новый пост{% endif %}
{% endblock %}

{% load user_filters %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if post %}Редактировать пост{% else %}Новый пост{% endif %}
          </div>
          <div class="card-body">

            <!--Валидация ошибок -->
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}

            <form method="post" enctype="multipart/form-data" action=" 
                {% if post %}
                  {% url 'posts:post_edit' post.id %}
                {% else %}
                  {% url 'posts:post_create' %}
                {% endif %}"
            >
              {% csrf_token %}

              <!-- Обход полей формы -->
              {% for field in form %}
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>

                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if post %}Сохранить{% else %}Добавить{% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  Подписки пользователя {{ user.username }}
{% endblock %}

{% block content %}
  {% include 'includes/switcher.html' %}  
  <div>
    <div class="mb-5">
      <article>
        {% for post in page_obj %}
          <ul>
            <li>
              Автор:
              <a href="{% url 'posts:profile' post.author.username %}">
                {{ post.author.get_full_name }}
              </a>
            </li>
            <li>
              Дата публикации: {{ post.created|date:"d E Y"}}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          {{ post.text|truncatechars:300|linebreaks }}
          <p>
            <a href="{% url 'posts:post_detail' post.pk %}">
              {% if post.text|length > 300 %}
                читать продолжение
              {% else %}
                подробная информация
              {% endif %}
            </a>
          </p>
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">#{{ post.group }}</a>
          {% endif %}
          {% if not forloop.last %}
            <hr>
          {% endif %}
        {% endfor %}
      </article>
    </div>
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title%}
  Записи группы - {{ group }}
{% endblock %}

{% block content %}
  <h1>{{ group}}</h1>
  <h5>{{ group.description|linebreaks }}</h5>
  <hr>
  {% for post in page_obj%}    
    <ul>
      <li>
        Автор: 
        <a href="{% url 'posts:profile' post.author.username %}">
          {{ post.author.get_full_name}}        
        </a>        
      </li>
      <li>
        Дата публикации: {{ post.created|date:"d E Y"}}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
	  <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    {{ post.text|linebreaks }}
    {% if not forloop.last %}<hr>{% endif %}

  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  Yatube - Главная страница
{% endblock %}
{% block content %}	
	{% include 'includes/switcher.html' %}
	{% load cache %}
	{% cache 20 index_page %}
    <h1>Последние обновления на сайте</h1>
	<div>
    {% for post in page_obj %}
      <ul>
        <li>
          Автор:
          <a href="{% url 'posts:profile' post.author.username %}">
            {{ post.author.get_full_name}}
          </a>
        </li>
        <li>
          Дата публикации: {{ post.created|date:"d E Y"}}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
	  {{ post.text|truncatechars:300|linebreaks }}
        <p>
          <a href="{% url 'posts:post_detail' post.pk %}">
            {% if post.text|length > 300 %}
              читать продолжение
            {% else %}
              подробная информация
            {% endif %}
          </a>
        </p>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">#{{ post.group }}</a>
      {% endif %}

      {% if not forloop.last %}
        <hr>
      {% endif %}

    {% endfor %}
	</div>
 {% endcache %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}

{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}

{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.created|date:"d E Y" }}
        </li>
        <!-- если у поста есть группа -->
        {% if post.group %}
          <li class="list-group-item">
            Группа:
            <a href="{% url 'posts:group_list' post.group.slug %}">
              {{ post.group }}
            </a>
          </li>
        {% endif %}

        <li class="list-group-item">
          Автор:
          <a href="{% url 'posts:profile' post.author.username %}">
            {{ post.author.get_full_name }}
          </a>
        </li>

        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span>{{ post.author.posts.count }}</span>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text|linebreaks }}
      </p>

      {% if user == post.author %}
        <hr>
        <div class="d-flex justify-content-end">
          <a href="{% url 'posts:post_edit' post.id %}" class="btn btn-primary" role="button">
            Редактировать пост
          </a>
        </div>
      {% endif %}
      <hr>
      {% include 'includes/comments.html' %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
  <div>
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ author.posts.count }}</h3>
    <div class="mb-5">
      {% if not user == author %}
        {% if following %}
          <a
                  class="btn btn-lg btn-light"
                  href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a
                  class="btn btn-lg btn-primary"
                  href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
      {% endif %}
    </div>
    <article>
      {% for post in page_obj %}
        <ul>
          <li>
            Дата публикации: {{ post.created|date:"d E Y"}}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        {{ post.text|truncatechars:300|linebreaks }}
        <p>
          <a href="{% url 'posts:post_detail' post.pk %}">
            {% if post.text|length > 300 %}
              читать продолжение
            {% else %}
              подробная информация
            {% endif %}
          </a>
        </p>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">#{{ post.group }}</a>
        {% endif %}
        {% if not forloop.last %}
          <hr>
        {% endif %}
      {% endfor %}
    </article>
  </div>
  {% include 'includes/paginator.html' %}
{% endblock %}